/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hid6tvfarfblbn5gegno3c2pvy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p43bbeocznex3dmlblm7kccb6e",
    "aws_cognito_identity_pool_id": "us-east-1:f6063b77-a9d9-45a6-ad34-4c951556e29e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_J7ovBLFYC",
    "aws_user_pools_web_client_id": "1g2eqp8b421r9titbsf98r6kfd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "image-bucket180843-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
